previous: Previous
next: Next
overview: Overview
table_contents: Table of Contents
slide: Slide
slides: Slides
start_presentation: Start now
demo: Demo
material: Material
share: Share
introduction: Introduction
published_by: Published by
start: Start
go_next_slide: Go to the next slide
go_prev_slide: Go to the previous slide
menu_title: Slides
close_menu: Close