previous: Previous
next: Next
overview: Overview
tableOfContents: Table of Contents
slide: Slide
slides: Slides
startPresentation: Start now
demo: Demo
material: Material
share: Share
createdBy: Created by
introduction: Introduction
publishedBy: Published by
slidesIndex: Slides Index
start: Start